repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.4
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: local
  hooks:
    - id: pytest
      name: pytest
      # pre-commit downloads uv and runs pytest using project environment
      entry: uv run pytest
      language: python
      additional_dependencies: [uv]
      pass_filenames: false
