[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yacsp"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "ponyawka" },
    { name = "uselessgoddes" },
]
dependencies = [
  # -- qt
  "qasync>=0.28",
  "PyQt6>=6.6",
  # -- auto
  "PyAutoIt>=0.6",
  "pyautogui>=0.9",
  "pyperclip>=1.11.0",
  "zxing-cpp",
  # -- win
  "pywin32>=311",
  "pyuac",
  "psutil",
  # -- api
  "uvicorn",
  "fastapi",
  "requests>=2.32.5",
  # -- vision
  "opencv-python>=4.12.0.88",
  "pyscreeze==0.1.28",
  "scipy>=1.16.3",
  "pillow>=12.0.0",
  "bettercam>=1.0.0",
  # --
  "tinydb>=4.8",
  "pydantic>=2.12.5",
  "typing-extensions>=4.8",
  # -- srt
  "icmplib>=3.0.4",
  "tzdata>=2025.2",
  "python-telegram-bot>=22.5",
  # -- nn
  "onnxruntime-directml>=1.23",
  "onnxruntime>=1.23",
  "selenium>=4.39.0",
  "webdriver-manager>=4.0.2",
  "steamio",
  "pathspec>=0.12.1",
]

[dependency-groups]
dev = [
  "ruff>=0.14",
  "ty>=0.0.8",
  "pre-commit",
  "pytest>=9.0.1",
  "nuitka",
]

[tool.ruff]
target-version = "py311"

line-length = 90
# sorry bro :)
indent-width = 2

[tool.ruff.lint]
ignore = ["F401", "N802", "N803", "N806", "N815"]
select = [
  "E",   # pycodestyle (error)
  "F",   # pyflakes
  "B",   # bugbear
  "B9",
  "C4",  # flake8-comprehensions
  "SIM", # flake8-simplify
  "I",   # isort
  "UP",  # pyupgrade
  "PIE", # flake8-pie
  "PGH", # pygrep-hooks
  "PYI", # flake8-pyi
]
# allow _unused variables
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ty.rules]
unused-ignore-comment = "warn"
redundant-cast = "ignore"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::RuntimeWarning"
]

[tool.uv.sources]
steamio = { git = "https://github.com/PONYAWKA/gc-handler" }
