[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yacsp"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "ponyawka" },
    { name = "uselessgoddes" },
]
dependencies = [
  # -- qt
  "qasync>=0.28",
  "PyQt6>=6.6",
  # -- auto
  "PyAutoIt>=0.6",
  "pyautogui>=0.9",
  "pyzbar>=0.1.9",
  # -- win
  "pywin32>=311",
  "pyuac",
  "psutil",
  # -- api
  "uvicorn",
  "fastapi",
  "steamio",
  "requests>=2.32.5",
  # -- vision
  "opencv-python>=4.12.0.88",
  "pyscreeze==0.1.28",
  "scipy>=1.16.3",
  "pillow>=12.0.0",
  "bettercam>=1.0.0",
  # --
  "tinydb>=4.8",
  "typing-extensions>=4.8",
  # -- srt
  "icmplib>=3.0.4",
  "tzdata>=2025.2",
  "python-telegram-bot>=22.5",
  # -- nn
  "onnxruntime-directml>=1.23",
  "onnxruntime>=1.23",
]

[dependency-groups]
dev = [
  "ruff>=0.14",
  "ty>=0.0.1a23",
  "pre-commit",
  "pytest>=9.0.1",
]

[tool.ruff]
target-version = "py311"

line-length = 80
# sorry bro :)
indent-width = 2

[tool.ruff.lint]
ignore = ["F401"]
select = ["E4", "E7", "E9", "F"]
# allow _unused variables
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.uv.sources]
steamio = { git = "https://github.com/PONYAWKA/gc-handler" }

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::RuntimeWarning"
]
